PCRM-9999 PCRM-0000 Demo fixes
NHSDigital/list-reconciliation pull request #138
Opened 2021-08-16 13:02 UTC by aparimoo-nhs

PDS API Retry refactor
LR-12 fix for address where address is not always has 5 items in list
LR-12 fix for Date accept where PDS may not send date
LR-11 fix where filter is for non sensitive patients instead of unrestricted

2021-08-16 14:34 UTC, joeds13 requested changes
The commit message still contains PCRM-9999, please remove it or use PCRM-0000

2021-08-16 16:03 UTC, josh-scargill-nhsd commented on packages/utils/pds_api_service.py
> +                    data_string=token,
We originally had a retry on this, since we don't now will it throw uncaught errors?

2021-08-16 16:03 UTC, josh-scargill-nhsd commented on packages/utils/pds_api_service.py
> +            return time_now > token_expiry_time
Assuming this is the best way to do this, I wonder if we should move it to a function to just check if expired?

2021-08-16 16:07 UTC, aparimoo-nhs commented on packages/lambda_code/LR_11_gp_registration_status/lr_11_lambda_handler.py
> +            ),
yes but earlier filter was on `U` as we have seen they are sending records with no markers, this ensures we are not processing any sensitive patients but allowing `U``and blank ones

2021-08-16 16:08 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +                    data_string=token,
Since it raises `toomanyupdates` it means other lambdas have already updated so no need to retry

2021-08-17 09:15 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +                return
I think this might as well not be defined since there are no more conditions that are specifically handled. You could be explicit and just do 
```
if status_code == 404 and error_code == "INVALIDATED_RESOURCE":
    # Patient Record is REDACTED
    redacted_patient_data = self.convert_pds_to_list_rec_data()
    redacted_patient_data.update(
        {"sensitive": SensitiveMarkers.REDACTED.value}
    )  # update dict with REDACTED
    return redacted_patient_data

else: 
    return
```

or just leave the `else` out

2021-08-17 09:15 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +            return True
I'd move the code you're not `try`ing outside the try/except. If ever there's a bug in the other function calls that raises a KeyError, it would be horrendous to track down. Something like this

```
time_now = datetime.datetime.now()
try:
    token_issue_time = str(token["issued_at"])[:10]
    token_expire_in_seconds = int(token["expires_in"])

except KeyError:
    # Token issued doesn't have required field
    return True

issue_datetime = datetime.datetime.fromtimestamp(int(token_issue_time))
token_expiry_time = issue_datetime + datetime.timedelta(0, token_expire_in_seconds)
return time_now > token_expiry_time
```

2021-08-17 09:15 UTC, jamesnunnnhs commented on packages/utils/ssm.py
> +        # ignore TooManyUpdates Exceptions as other lambda have already updated the token
Maybe worth clarifying in the comment why you're catching `ClientError` rather than `TooManyUpdates` for this

2021-08-17 10:53 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_11_gp_registration_status/lr_11_lambda_handler.py
> +            ),
Oh hang on, just spotted the `~` which i'm assuming is a "not this"

2021-08-17 11:36 UTC, jamesnunnnhs approved these changes

2021-08-17 12:18 UTC, abbas-khan8 approved these changes

2021-08-17 12:51 UTC, HarveyNHS reviewed
Please review

2021-08-17 12:51 UTC, HarveyNHS commented on packages/utils/pds_api_service.py
> +class ExpiredTokenError(Exception):
Are we also handling 500 errors aswell?

2021-08-17 12:57 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +class ExpiredTokenError(Exception):
Yes, status code other than 200/4xx will raise PDSAPI Exception

2021-08-17 14:17 UTC, josh-scargill-nhsd commented on packages/utils/pds_api_service.py
> +            if self._is_token_valid():
To clarify, is this right?
The name would suggest it only enters this code if true.
```
Is token valid? 
    yes? recheck the token
    no? don't need to recheck the token
```

2021-08-17 14:57 UTC, jamesnunnnhs commented on packages/utils/ssm.py
> +    except ClientError:
@joeds13

2021-08-17 15:22 UTC, joeds13 approved these changes

2021-08-17 15:26 UTC, merged