PCRM-8888 Add pytest artifacts in workflow
NHSDigital/list-reconciliation pull request #139
Opened 2021-08-16 15:42 UTC by aparimoo-nhs

Pytest artifacts

2021-08-16 15:44 UTC, joeds13 requested changes
The commit message still contains PCRM-8888, please remove it or use PCRM-0000

2021-08-16 16:05 UTC, josh-scargill-nhsd approved these changes

2021-08-17 09:16 UTC, jamesnunnnhs approved these changes

2021-08-17 10:42 UTC, joeds13 approved these changes

2021-08-17 10:49 UTC, merged