PCRM-4721 - remove post office lambda and associated resources
NHSDigital/list-reconciliation pull request #326
Opened 2021-12-02 17:41 UTC by antonyibbotson1-nhs

2021-12-03 15:48 UTC, Hobdell requested changes

2021-12-03 15:48 UTC, Hobdell commented on packages/lr_logging/list_reconciliation_logs.cfg
>  [LR25I02]
Remove all log config related to the post office lambda

2021-12-06 09:08 UTC, antonyibbotson1-nhs commented on packages/lr_logging/list_reconciliation_logs.cfg
>  [LR25I02]
Nice spot, removed other LR25 refs

2021-12-07 12:32 UTC, johnwaghorn approved these changes

2021-12-07 15:26 UTC, Hobdell approved these changes

2021-12-07 15:27 UTC, merged