Pcrm 3731 spike
NHSDigital/list-reconciliation pull request #46
Opened 2021-07-13 13:30 UTC by jamesnunnnhs

2021-07-14 15:07 UTC, abbas-khan8 commented on packages/lambda_code/LR_02_validate_and_parse/lr_02_lambda_handler.py
>              Appends 'Id' field to each validated patient record in records
docstring needs updating to match new purpose?

2021-07-14 15:09 UTC, abbas-khan8 commented on packages/lambda_code/LR_02_validate_and_parse/lr_02_lambda_handler.py
>          practice_code = validated_file["practice_code"]
Since a chunk of the original functionality to do with `validated_file` dict has been removed, maybe this function just needs `practice_code` string?

2021-07-14 15:13 UTC, abbas-khan8 commented on packages/lambda_code/LR_02_validate_and_parse/lr_02_lambda_handler.py
> +            self.write_to_dynamodb(validated_file, num_of_records)
Since a chunk of the original functionality to do with validated_file dict has been removed from `write_to_dynamodb`, maybe this function just needs practice_code string as a parameter?

2021-07-16 09:06 UTC, joeds13 requested changes

2021-07-16 09:06 UTC, joeds13 commented on terraform/modules/lambda/LR-07/iam.tf
> +  lr-06-bucket_arn = "arn:aws:s3:::${var.lr-06-bucket}"
We should pass the ARN in here, rather than constructing it in a string

2021-07-16 09:06 UTC, joeds13 commented on terraform/modules/s3/outputs.tf
> +    LR-06 = {
Move to line 31

Keep the numerical ordering of buckets?

2021-07-16 09:06 UTC, joeds13 commented on terraform/stacks/list-reconciliation/modules.tf
> +  count        = local.environment != "prod" ? 1 : 0
I like to add spacing here, as it separates the module meta arguments "source"/"count" from the actual module variables "suffix"/"LR_22_bucket"/etc just makes it a bit clearer to read later

2021-07-16 09:53 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_24_save_records_to_s3/lr24_lambda_handler.py
> +class SaveRecordsToS3(LambdaApplication):
I thought we discussed that this was to be a generic bucket saving mechanism?

2021-07-16 09:53 UTC, josh-scargill-nhsd commented on packages/utils/database/models.py
> +        write_capacity_units = 1000
Can we do this on others if they're on 1 too? in case it does affect, I don't think we want 1 anywhere

2021-07-16 09:53 UTC, josh-scargill-nhsd commented on terraform/modules/lambda/LR-08/iam.tf
> +                "dynamodb:PutItem"
Doesn't it just need 1 of these?

2021-07-16 09:56 UTC, jamesnunnnhs commented on packages/utils/database/models.py
> +        write_capacity_units = 1000
Er yeah I can change the rest, but I really don't know where that one came from, I didn't touch these

2021-07-16 09:59 UTC, joeds13 commented on packages/utils/database/models.py
> +        write_capacity_units = 1000
Do we want to define these in Terraform, rather than in the code?

We may want them to differ per env, if they are provisioned capacity units they incur standing charges that we won't want in Dev

2021-07-16 10:37 UTC, jamesnunnnhs commented on terraform/modules/lambda/LR-08/iam.tf
> +                "dynamodb:PutItem"
yes

2021-07-16 10:38 UTC, jamesnunnnhs commented on packages/utils/database/models.py
> +        write_capacity_units = 1000
I still think it's arbitrary-  the rest are set to 100, keep the same? or all set to 1000? or 100?

2021-07-16 11:15 UTC, jamesnunnnhs commented on packages/utils/database/models.py
> +        write_capacity_units = 1000
Thing is @joeds13 that these are needed for the python lib to work but don't actually do anything in practice except if we use the python lib to provision the tables, which we don't. They do nothing in this case which is why they are set to 1 on the other tables, I don't believe there's any throttling or retrying based on these values

2021-07-16 11:22 UTC, jamesnunnnhs commented on packages/utils/database/models.py
> +        write_capacity_units = 1000
So yes they should be set in terraform if it's moved from on demand to provisioned.

2021-07-16 11:25 UTC, jamesnunnnhs commented on packages/lambda_code/LR_24_save_records_to_s3/lr24_lambda_handler.py
> +class SaveRecordsToS3(LambdaApplication):
you're right, I forgot that bit

2021-07-19 12:36 UTC, josh-scargill-nhsd commented on packages/utils/database/models.py
> +        write_capacity_units = 1000
Since we don't know whats going on under the hood, I think making them all 1000 is a safe bet to avoid any potentially throttling that we aren't anticipating

2021-07-19 12:56 UTC, joeds13 approved these changes

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +        job_id = body["job_id"]
Why is this created here instead of in the patient?

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +        else:
Since all the exceptions raise an error, is this `else` required? code the code below not be part of the main body?

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
>              raise
I'm not sure if this is needed? In the event `PDSAPIError` is raised, it's going to stop the application been processed no?

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_24_save_records_to_s3/lr24_lambda_handler.py
> +
Can we move `try` down a line, so it has a new line above, and no new line below

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_24_save_records_to_s3/lr24_lambda_handler.py
> +            except Exception as err:
new line before except

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_24_save_records_to_s3/lr24_lambda_handler.py
> +                    f"{id_}/{id_}.json",
Not sure we want it like this do we? aka: `myUniqueId/myUniqueId.json`, seems a bit unusual 🤔

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on packages/services/split_records_to_s3.py
> +    max_size: int = 128 * 1024,
Not sure if we want to make this available, couldn't the caller pass in too high a value and cause it to fail?

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on test/unittests/lambdas/LR_24_save_records_to_s3/test_LR_24_save_records_to_s3.py
> +                    "practice_code": "Y12345",
Since these 2 objects are going to be the same, can we store them as variables instead? just shortens the test to make it a bit more readable :)

2021-07-19 12:58 UTC, josh-scargill-nhsd commented on test/unittests/lambdas/LR_24_save_records_to_s3/test_LR_24_save_records_to_s3.py
> +def test_save_records_to_s3_saves_records(
I'd expect a test for the exception been thrown as expected. And the retrying logic if we aren't testing it elsewhere?

2021-07-19 13:01 UTC, jamesnunnnhs commented on packages/lambda_code/LR_24_save_records_to_s3/lr24_lambda_handler.py
> +                    f"{id_}/{id_}.json",
It makes no difference to the logic but it does get round a limit I was hitting where you can only have so many requests per second under a single prefix (i.e. s3 folder). Creating a new prefix for each file means unlimited rps

2021-07-19 13:02 UTC, jamesnunnnhs commented on packages/services/split_records_to_s3.py
> +    max_size: int = 128 * 1024,
they could want set it lower

2021-07-19 13:24 UTC, jamesnunnnhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +        job_id = body["job_id"]
because job_id is used in loads of places after this point

2021-07-20 07:59 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +        job_id = body["job_id"]
but we could just use patient.JobId instead if we set that since it's set directly below no?

2021-07-21 07:57 UTC, josh-scargill-nhsd approved these changes

2021-07-21 08:29 UTC, abbas-khan8 approved these changes

2021-07-21 12:08 UTC, merged