PCRM-3515 -  Feedback GP extract validation errors
NHSDigital/list-reconciliation pull request #47
Opened 2021-07-14 13:53 UTC by abbas-khan8

- Triggers on LOG file creation in s3 `fail/` folder
- Reads and validates LOG file, and constructs email stub message from contents
- Deletes failed file and LOG file once consumed

2021-07-16 09:00 UTC, joeds13 requested changes

2021-07-16 09:00 UTC, joeds13 commented on terraform/modules/lambda/lambda.tf
> +  depends_on        = [module.LR-02.LR_02_lambda]
We shouldn't need to use this to create a dependency

If it is needed, we should be passing through some resources/data from that module, then when terraform creates it's DAG it will be able to see the dependency itself

2021-07-16 09:27 UTC, jamesnunnnhs commented on packages/lambda_code/LR_02_validate_and_parse/lr_02_lambda_handler.py
> +            str: JSON dump of error log dict containing Job ID, practice code, filename and error message/s.
I'd recommend just returning a dict, then converting to json as late as possible, just makes it easier to read what you need from the object until you dump as text.

2021-07-16 09:27 UTC, jamesnunnnhs commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +        to = "test@nhs.net"
This needs to be an environment variable I believe, and it will need to be set per terraform environment

2021-07-16 09:27 UTC, jamesnunnnhs commented on terraform/modules/lambda/LR-02/lambda.tf
> +      INFLIGHT_TABLE                     = var.in_flight_table_arn
Is it correct to change this? The arn works with pynamodb does it?

2021-07-16 10:14 UTC, abbas-khan8 commented on packages/gp_file_parser/file_name_parser.py
> +        msg = ["Filename exceeds character limit"]
It's for consistency really, some error messages (filename errors/invalid records) can contain multiple errors so returning error inside a list here so the structure of the log looks the same

2021-07-16 10:17 UTC, abbas-khan8 commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +        to = "test@nhs.net"
This is a stub atm, it will be expanded and improved in a later PR. That being said the implementation code they provided us with don't use env variables for any of the email components

2021-07-16 10:18 UTC, abbas-khan8 commented on terraform/modules/lambda/LR-02/lambda.tf
> +      INFLIGHT_TABLE                     = var.in_flight_table_arn
Nope I'm not 100% why this has changed tbh, it's a mistake

2021-07-16 10:34 UTC, josh-scargill-nhsd reviewed
I assume testers are happy you've noodled with their tests?

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +                "message": "LR-04 successfully read and validated log file",
For which job?

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +                "message": "LR-04 successfully sent email",
For which job?

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +        )
Are we wanting to remove log files? Is the process that a job fails we're referring purely to splunk to see what went wrong? as I don't think the information in their is substantial enough

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +        self.validate_log()
Looking at how you set your code up, i'd suggest this call was in the parent function

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +FAILED_PREFIX = "fail/"
This is used in multiple places, I question that we should be storing this somewhere more generic now

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +            assert f"{self.log['file']}_LOG.json" == log_name
We've discussed before not to use `assert` in none test code

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +    def validate_log(self):
This function seems a bit strange.

If you're validating if things are ok, maybe go with a more standard approach of `if something bad, raise something`?

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +                if record["TRANS_ID"] != "None":
I don't see an else, wasn't this the line number conversation?

2021-07-16 10:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +    def create_body(self) -> str:
Looking at this, it doesn't seem to match the spec noted here https://nhsd-confluence.digital.nhs.uk/display/PCRM/PCRM-3515+%28PDS-299%29+-+Identify+any+data+validation+errors

2021-07-16 10:46 UTC, abbas-khan8 commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +                if record["TRANS_ID"] != "None":
Where would the line number come from? The parser would have to be changed to store line numbers wouldn't it?

2021-07-16 10:49 UTC, abbas-khan8 commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +                "message": "LR-04 successfully read and validated log file",
There is not Job, a Job item is only created if validation passed

2021-07-16 10:54 UTC, abbas-khan8 commented on packages/lambda_code/LR_04_feedback_failure/lr_04_lambda_handler.py
> +        )
I don't have a preference, I'm not against keeping the log files. At this point there is no job, once an email has been sent back to PCSE informing them of the failed file the process is complete right? The log file never has to be mentioned or used again, unless we want to retain it as proof?

2021-07-16 14:13 UTC, abbas-khan8 commented on terraform/modules/lambda/LR-02/lambda.tf
> +      INFLIGHT_TABLE                     = var.in_flight_table_arn
This was a mistake, I've reverted changes in latest push

2021-07-19 09:23 UTC, jamesnunnnhs commented on packages/gp_file_parser/file_name_parser.py
> +        msg = ["Filename exceeds character limit"]
So you try to parse what you can and return multiple errors if there are multiple with just the filename?

2021-07-19 12:59 UTC, HarveyNHS reviewed
Added review

2021-07-19 12:59 UTC, HarveyNHS commented on test/integrationtests/specs/lr_02_lambda_others.spec
> +Tags: wip
Hey Abbas, I've noticed you've added wips tags to these tests, are you checking for something within the Githubs pipeline?

2021-07-19 13:24 UTC, abbas-khan8 commented on test/integrationtests/specs/lr_02_lambda_others.spec
> +Tags: wip
Hi Harvey, these have been marked WIP due to a convo had with Prem. Because the LOG file was getting deleted from the fail/ folder once consumed in the process, the integration tests which were checking for the existence/validity of the LOG file were failing as the file had been deleted

2021-07-21 11:16 UTC, abbas-khan8 commented on packages/gp_file_parser/file_name_parser.py
> +        msg = ["Filename exceeds character limit"]
LR04 will treats any filename errors as a list when it comes to processing these messages, because there's a chance this will return more than one error message. I get this might not be the most efficient way but the rewriting/reformatting required to change this would result in very little performance increase, is it worth it or is there another issue that I'm not seeing here?

2021-07-22 14:23 UTC, jamesnunnnhs commented on packages/gp_file_parser/file_name_parser.py
> +        msg = ["Filename exceeds character limit"]
nope just wondering

2021-07-22 14:25 UTC, joeds13 approved these changes

2021-07-23 08:03 UTC, jamesnunnnhs approved these changes

2021-07-23 09:14 UTC, merged