PCRM-3989 - Adds logging and versioning to buckets
NHSDigital/list-reconciliation pull request #48
Opened 2021-07-15 13:16 UTC by jamesnunnnhs

2021-07-15 13:22 UTC, joeds13 requested changes

2021-07-15 13:22 UTC, joeds13 commented on terraform/modules/s3/LR-01.tf
> +    target_prefix = "log/"
Might be better to namespace the logs on each bucket:
`target_prefix = "lr-01-gp-extract-input-${var.suffix}/"`

As the files just turn up as `s3://list-rec-access-logs-jamesnunn/log/2021-07-15-13-13-03-329E618F5B874B67`

2021-07-15 13:46 UTC, joeds13 approved these changes

2021-07-15 14:37 UTC, premnhs approved these changes
LGTM

2021-07-16 08:28 UTC, aparimoo-nhs approved these changes

2021-07-16 08:48 UTC, merged