PCRM-3538 LR-25 MESH Post Office Lambda
NHSDigital/list-reconciliation pull request #49
Opened 2021-07-15 13:23 UTC by joeds13

When open, delivers messages from Mesh inbound directories to their
intended List Reconciliation targets

2021-07-16 08:24 UTC, aparimoo-nhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +            return
I think `return ` is not needed , `self.response` is suffice

2021-07-16 08:24 UTC, aparimoo-nhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        mesh_bucket_id = os.environ.get("MESH_BUCKET_ID")
this should be `self.system_config['MESH_BUCKET_ID']`

2021-07-16 08:24 UTC, aparimoo-nhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        if os.environ.get("POST_OFFICE_OPEN") == "True":
should be `self.system_config["POST_OFFICE_OPEN"]`

2021-07-16 08:24 UTC, aparimoo-nhs commented on terraform/modules/lambda/lambda.tf
> +  # mesh_post_office_open = var.mesh_post_office_open
do you need this comment ?

2021-07-16 08:24 UTC, aparimoo-nhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        s3r = boto3.resource("s3")
consider using  exception catching

2021-07-16 08:24 UTC, aparimoo-nhs commented on Makefile
> +	pytest
why removed ignored? this will start discovering `integrationtests ` which will fail

2021-07-16 08:24 UTC, aparimoo-nhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        self.response = '{"post_office": "open"}'
I think `return ` is not needed , `self.response` is suffice

2021-07-16 09:52 UTC, joeds13 commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +            return
https://github.com/NHSDigital/spine-core-aws-common#usage

Pattern taken from the docs

2021-07-16 09:53 UTC, joeds13 commented on Makefile
> +	pytest
https://github.com/NHSDigital/list-reconciliation/blob/develop/pytest.ini#L37

You already define the ignore in the `pytest.ini` we don't need the duplication of the cli flag

2021-07-16 09:54 UTC, joeds13 commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        self.response = '{"post_office": "open"}'
Again, taken from https://github.com/NHSDigital/spine-core-aws-common#usage

2021-07-19 14:09 UTC, joeds13 commented
Blocked my https://github.com/NHSDigital/spine-core-aws-common/pull/33

2021-07-20 14:45 UTC, jamesnunnnhs requested changes

2021-07-20 14:45 UTC, jamesnunnnhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +            self.response = '{"post_office": "closed"}'
is it worth reusing the same message in the response?
```
msg = 'post office status closed'
{    ...
     "message": msg,
    ...
}
self.response = json.dumps({"status": msg})
```
Also personally I try to not define literal json - instead define literal dicts and then `json.dumps` as it helps prevent any malformed handwritten json.

2021-07-20 14:45 UTC, jamesnunnnhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +                objects.append(object.key)
Use this with the `Prefix` arg to avoid your own loop?https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2

2021-07-20 14:45 UTC, jamesnunnnhs commented on terraform/modules/lambda/LR_25_mesh_post_office/iam.tf
> +        "arn:aws:s3:::${statement.value.outbound.bucket}"
I think you asked me previously to use a predefined arn rather than construct a bucket arn from the name ;-)

2021-07-20 14:45 UTC, jamesnunnnhs commented on terraform/modules/lambda/LR_25_mesh_post_office/iam.tf
> +        "arn:aws:s3:::${statement.value.outbound.bucket}"
ditto the ones below

2021-07-20 14:45 UTC, jamesnunnnhs commented on test/unittests/lambdas/LR_25_mesh_post_office/test_LR_25_mesh_post_office.py
> +#     assert response == expected
If you want to keep the code, uncomment and just mark it with `@pytest.mark.skip('conflict due to caching of SSM Parameters in the spine_aws_common library')`

2021-07-20 14:57 UTC, joeds13 commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +                objects.append(object.key)
Yeah I thought about this, but I couldn't find a way to list with both the prefix and suffix check, as we want to ignore "directories" so never rewrote this one

Still not sure if there's a cleaner way to do both prefix/suffix on list and this piece of code is not very performance sensitive, so not sure how much effort it's worth looking into?

2021-07-20 15:03 UTC, joeds13 commented on terraform/modules/lambda/LR_25_mesh_post_office/iam.tf
> +        "arn:aws:s3:::${statement.value.outbound.bucket}"
Yeah, I was expecting this one...

Issue here is that we need access to an ARN which is unknown, the var's (`statement.value.*.bucket`) get passed in as config to the module, so we could just require ARNs to be passed in there, but that just moves the problem

We could also use the `aws_s3_bucket` data resource, to lookup the ARN via the name, but that isn't so clean or easy to pass into this loop, with the language functions that terraform provides, so I'm not really a fan of that either

Happy to be challenged further

2021-07-20 15:17 UTC, jamesnunnnhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +                objects.append(object.key)
I'm not sure what you mean by suffix too, if you mean the trailing `'/'` then that should be handled by setting the prefix to `list_objects_v2(..., Prefix='yourprefix/',...)`. I'll leave it up to you, just might be a bit cleaner.

2021-07-20 15:17 UTC, jamesnunnnhs commented on terraform/modules/lambda/LR_25_mesh_post_office/iam.tf
> +        "arn:aws:s3:::${statement.value.outbound.bucket}"
Nope, terraform isn't my strong suit I trust you know what's best then.

2021-07-20 15:20 UTC, aparimoo-nhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        if self.mesh_post_office_open == "True":
why not use `self.system_config["mesh_post_office_open"]` ?

2021-07-20 15:20 UTC, aparimoo-nhs commented on terraform/modules/lambda/lambda.tf
> +    lr_25 = "LR_25_mesh_post_office"
not consistent with other names . see cases

2021-07-20 15:20 UTC, joeds13 commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +                objects.append(object.key)
No you're right, I _was_ thinking if a file was put in on the key `yourprefix/dir/message.txt` it would pick up `yourprefix/dir/` as a key, but it'd only do that if someone/thing explicitly created that key, but that's fairly unlikely

2021-07-20 15:43 UTC, joeds13 commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        if self.mesh_post_office_open == "True":
I followed the pattern of other uses of the the Spine common library by creating class variables of configuration and using them

2021-07-20 15:47 UTC, joeds13 commented on terraform/modules/lambda/lambda.tf
> +    lr_25 = "LR_25_mesh_post_office"
https://nhsd-confluence.digital.nhs.uk/display/PCRM/Terraform+Design+Choices

Inconsistent with existing, consistent with the design choices we all discussed and agree to try to adopt

It'd be a massive scope creep to start changing all of these on this PR to match, so I'm a fan of just writing new code as desired and uplifting old code as it's touched, makes sure we're not adding more debt that needs changing in the future

2021-07-20 16:55 UTC, aparimoo-nhs commented on terraform/modules/lambda/lambda.tf
> +    lr_25 = "LR_25_mesh_post_office"
fair enough

2021-07-21 08:29 UTC, josh-scargill-nhsd commented on test/unittests/lambdas/LR_25_mesh_post_office/conftest.py
> +    In ever test, set the environ to minimally mimic what Lambda runtime sets,
*every

2021-07-21 08:29 UTC, josh-scargill-nhsd commented on test/unittests/lambdas/LR_25_mesh_post_office/test_LR_25_mesh_post_office.py
> +    """
I'm expecting the test name to be clear enough not to require a comment in most scenarios

2021-07-26 09:10 UTC, joeds13 commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +                objects.append(object.key)
After finally getting a chance to look at this, setting `Prefix='yourprefix/'` still returns the object `yourprefix/`, so we'd still want to remove that from the returned items list, so going to leave this code as is

2021-07-26 09:33 UTC, aparimoo-nhs commented on terraform/stacks/list-reconciliation/locals.tf
> +    preprod = "False"
should this be `prod`?

2021-07-26 09:35 UTC, aparimoo-nhs commented on test/unittests/lambdas/LR_25_mesh_post_office/conftest.py
> +@pytest.fixture(scope="class")
`class` ? i dont see any `class`? can it be `module` ?

2021-07-26 09:35 UTC, aparimoo-nhs commented on test/unittests/lambdas/LR_25_mesh_post_office/conftest.py
> +@pytest.fixture(scope="class")
may be `module`?

2021-07-26 09:38 UTC, aparimoo-nhs commented on terraform/modules/lambda/lambda.tf
> +
doesn't look it is formatted ? is the new line intentional

2021-07-26 09:38 UTC, jamesnunnnhs approved these changes
Approved with comment to implement if it's worth it/possible

2021-07-26 09:38 UTC, jamesnunnnhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        return False
Whenever I see string representations of true/false I see a bug. If it's possible to use a boolean value for this in terraform and it be easily passed then that would be good. If not, this is ok.

2021-07-26 09:38 UTC, jamesnunnnhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +                objects.append(object.key)
Righto

2021-07-26 09:40 UTC, joeds13 commented on terraform/modules/lambda/lambda.tf
> +
I find it's more to have a space between the modules meta variables (source/count/for_each etc) and it's variables

2021-07-26 09:43 UTC, joeds13 commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        return False
Yeah fully agree, but in this case it's an SSM Parameter being picked up by the LambdaApplication class

SSM Params only have string types:
`String | StringList | SecureString`
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PutParameter.html#API_PutParameter_RequestSyntax

So there isn't away to treat it as a bool

2021-07-26 09:53 UTC, joeds13 commented on test/unittests/lambdas/LR_25_mesh_post_office/conftest.py
> +@pytest.fixture(scope="class")
Set both to function (https://github.com/spulec/moto#example-on-pytest-usage)

2021-07-26 09:55 UTC, jamesnunnnhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        self.mesh_post_office_open: str = str(self.system_config["mesh_post_office_open"])
Environment vars are conventionally capitalised, which should be reflected here IMO

2021-07-26 09:57 UTC, joeds13 commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        self.mesh_post_office_open: str = str(self.system_config["mesh_post_office_open"])
These are not env vars, they are SSM Parameters and need to match directly, with full names for example:
- `/LR_25_mesh_post_office-pcrm-3538-bf63187e/mappings`
- `/LR_25_mesh_post_office-pcrm-3538-bf63187e/mesh_post_office_open`
I would not normally capitalise these

2021-07-26 10:07 UTC, jamesnunnnhs commented on packages/lambda_code/LR_25_mesh_post_office/lr_25_lambda_handler.py
> +        self.mesh_post_office_open: str = str(self.system_config["mesh_post_office_open"])
yep ok

2021-07-26 10:08 UTC, josh-scargill-nhsd commented on terraform/modules/lambda/variables.tf
> +
🚌

2021-07-26 10:08 UTC, josh-scargill-nhsd commented on terraform/stacks/list-reconciliation/locals.tf
> +    prod = []
Do we need to note anywhere that this will need populating at some point?

2021-07-26 10:17 UTC, joeds13 commented on terraform/stacks/list-reconciliation/locals.tf
> +    prod = []
Added to the Prod Env Setup ticket: https://nhsd-jira.digital.nhs.uk/browse/PCRM-3847

2021-07-26 10:51 UTC, aparimoo-nhs approved these changes

2021-07-27 07:56 UTC, merged