PCRM-3852-Test-Coverage
NHSDigital/list-reconciliation pull request #52
Opened 2021-07-15 23:09 UTC by HarveyNHS

Test Coverage for PCRM-3852

2021-07-16 08:26 UTC, premnhs commented on test/integrationtests/specs/lr_only_on_pds_process.spec
> +
remove this empty line

2021-07-16 08:26 UTC, premnhs commented on test/integrationtests/specs/lr_only_on_pds_process.spec
> +
same here

2021-07-16 08:35 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +test_datetime = get_datetime_now()
The convention is that all your top level constants should be capitalised - it makes it much easier to see where it is defined

2021-07-16 08:40 UTC, jamesnunnnhs requested changes

2021-07-16 08:40 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +    if response.get("Contents") != None:
Doesn't this mask a failing condition if the file doesn't exist? Maybe better to remove this check?

Please check the other patterns like this, and also `if "Contents" in lr_22_response:` is the same check.

2021-07-16 09:01 UTC, premnhs commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +        assert ext == ".csv"
Is it similar to the steps in `lr_10_12_13_onlyon_pds.py` ( step : "connect to lr-13 and check output csv file content and file format as expected") 

Why cant this step be used ?

2021-07-16 09:01 UTC, premnhs commented on test/integrationtests/specs/lr_only_on_pds_process.spec
> +
Can these tests be added as part of this spec 
`  lr_10_12_13_lambda_onlyon_pds.spec`

2021-07-19 13:16 UTC, josh-scargill-nhsd requested changes

2021-07-19 13:16 UTC, josh-scargill-nhsd commented on main.py
> +import os
This file shouldn't be committed in

2021-07-19 13:29 UTC, premnhs commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +
why there is a line space here ?

2021-07-19 13:29 UTC, premnhs commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +
same here ?

2021-07-19 13:31 UTC, premnhs commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +
same here

2021-07-20 14:50 UTC, jamesnunnnhs approved these changes

2021-07-21 09:06 UTC, premnhs approved these changes
LGTM

2021-07-21 09:06 UTC, josh-scargill-nhsd approved these changes

2021-07-21 09:09 UTC, merged