Pcrm 3662 manage sensitive patients
NHSDigital/list-reconciliation pull request #55
Opened 2021-07-19 17:02 UTC by aparimoo-nhs

- Added Sensitive patients filtering
-  Mock FHIR Rest API

2021-07-22 08:57 UTC, joeds13 requested changes

2021-07-22 08:57 UTC, joeds13 commented on .github/workflows/python-package.yml
> +          pytest test/unittests
Should be changed to `make unittests`

2021-07-22 08:57 UTC, joeds13 commented on Makefile
> +	pytest test/unittests
What's the benefit of moving this out of `pytest.ini`?

2021-07-22 08:57 UTC, joeds13 commented on packages/utils/pds_api_service.py
> +        # self.log_object.write_log(
Should this be in or out?

2021-07-22 08:57 UTC, joeds13 commented on packages/utils/pds_api_service.py
> +                # self.log_object.write_log(
Should this be in or out?

2021-07-22 08:57 UTC, joeds13 commented on pytest.ini
> +    PDS_URL="http://test_url:80000/patient"
Port `80000` is too large to be valid?

This should be a sane default, so whatever port the mock FHIR API uses when run locally

2021-07-22 08:57 UTC, joeds13 commented on requirements.txt
> +fastapi~=0.66.0
Putting these here will increase all Lambda packaging sizes, just for a dev dependency, they should be moved and packaged separately just for the mock api

2021-07-22 08:57 UTC, joeds13 commented on terraform/modules/mock_fhir_api/iam.tf
> +  name               = "suffix-mock-fhir-role-${var.suffix}"
`suffix` in start of name should be removed

2021-07-22 08:57 UTC, joeds13 commented on terraform/modules/mock_fhir_api/iam.tf
> +      "arn:aws:lambda:*:*:function:${aws_lambda_function.mock_fhir_api_lambda.arn}"
This doesn't look correct, it looks like it'll concatenate two ARNs: as you have one in the string and one from the resource attribute

2021-07-22 08:57 UTC, joeds13 commented on terraform/modules/mock_fhir_api/iam.tf
> +    resources = ["arn:aws:s3:::${var.pds_bucket}/*"]
Should pass in the full ARN rather than constructing

2021-07-22 08:57 UTC, joeds13 commented on terraform/modules/mock_fhir_api/lambdas.tf
> +  # depends_on = [null_resource.install_python_dependencies]
Remove unneeded

2021-07-22 08:57 UTC, joeds13 commented on terraform/modules/mock_fhir_api/lambdas.tf
> +  output_path = "${path.module}/../../../api_lamdab_layer.zip"
Typo `api_lamdab_layer`

2021-07-22 08:57 UTC, joeds13 commented on terraform/stacks/mock-fhir-api/locals.tf
> +  terraform_deploy_role_arn = {
We only want this to deploy in `dev`, so you can remove `preprod/prod`

2021-07-22 08:57 UTC, joeds13 commented on terraform/stacks/mock-fhir-api/locals.tf
> +    Project            = "ListReconciliation"
Make this unique, I'd suggest `"ListReconciliationMockPDS"`

2021-07-22 08:57 UTC, joeds13 commented on terraform/modules/mock_fhir_api/lambdas.tf
> +data "archive_file" "ontology_api_lambda_archive" {
Think we need some more consistent naming:
- ontology_api
- fhir_mock_api
- pds_api
- mock_fhir_api
- Mock-API

Can we standardise on one name?

2021-07-22 08:57 UTC, joeds13 commented on terraform/stacks/mock-fhir-api/modules.tf
> +module "test_data" {
Despite this being in a separate stack, this will cause a collision with the `test_data` bucket in the `list-reconciliation` stack

We also don't need the test data in two buckets

I'd suggest you break out the data you need from this module and just put it in the `Mock-API` module to keep it self contained and avoid the collision

2021-07-22 08:57 UTC, joeds13 commented on terraform/stacks/mock-fhir-api/modules.tf
> +module "s3" {
Is this needed? This will create a whole set of all the List-Rec Buckets?

If there is data needed, move/copy it into the Mock-API module to keep it self contained

2021-07-22 08:57 UTC, joeds13 commented on terraform/stacks/mock-fhir-api/outputs.tf
> +output "region" {
Do we need this?

2021-07-22 08:57 UTC, joeds13 commented on terraform/stacks/mock-fhir-api/terraform.tf
> +    key            = "list-reconciliation.tfstate"
This should be the stack name, otherwise you can overwrite/collide Terraform states

2021-07-22 09:10 UTC, aparimoo-nhs commented on pytest.ini
> +    PDS_URL="http://test_url:80000/patient"
It is typo i change it to 8000, it is a fake url

2021-07-22 09:10 UTC, aparimoo-nhs commented on terraform/stacks/mock-fhir-api/outputs.tf
> +output "region" {
no , copy pasted. Deleted it now

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +import boto3
already got this import on line 7

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +from utils.pds_api_service import FHIRAPIHelper
combine these imports?

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/lambda_code/LR_12_pds_registration_status/lr_12_lambda_handler.py
> +                    if any(x in pds_record.get("sensitive") for x in ["R", "V", "REDACTED"]):
couldn't you simplify this?
```
if pds_record.get("sensitive") in ["R", "V", "REDACTED"]:
    ....
```

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> -
I think these newlines are part of the convention for google-style docstrings: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +class FHIRAPIHelper:
since we have this now, shouldn't you delete the other functions it deprecates? get_pds_record, get_pds_fhir_record, get_mock_pds_record, PDSAPIError?

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +            pds_record = self.pds_api.get_pds_record(record.NhsNumber)
Will we be reimplementing (or be able to reimplement) the retries and backoff factor in the new pds interface?

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +    def get_pds_record(self, nhs_id) -> dict:
Recommend renaming this to nhs_number because that's it's name

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +            print(str(e))
Yeah this could be just allowed to raise (or reraise custom) and catch it in the lambda and log it there

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +            issue_code = self.parse_json_data("issue.[*].details.coding.[*].code")
if the response is 200, does this object exist?

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +        :field is a jsonpath field
We've gone down the google style docstring route: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2021-07-22 11:56 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +            return match_data[0]
Could just do this?:
```
for item in json_expr.find(self.pds_data):
    return item.value
```

2021-07-22 11:56 UTC, jamesnunnnhs commented on requirements.txt
> +jsonpath-ng==1.5.3
Are all of these direct dependencies of our code? They seem like deps of deps which we could just not worry about

2021-07-22 18:27 UTC, joeds13 commented on terraform/modules/mock_fhir_api/api_gateway.tf
> +resource "aws_api_gateway_deployment" "mock_fhir_api_deployment" {
Are there any access controls we can add here to restrict access to only the List Reconciliation account rather than it being publically accessible?

2021-07-23 15:06 UTC, aparimoo-nhs commented on terraform/modules/mock_fhir_api/lambdas.tf
> +data "archive_file" "ontology_api_lambda_archive" {
done

2021-07-25 15:16 UTC, aparimoo-nhs commented on .github/workflows/python-package.yml
> +          pytest test/unittests
Done

2021-07-25 15:19 UTC, aparimoo-nhs commented on Makefile
> +	pytest test/unittests
This breaks imports in tests  if we don't use relative path of tests hence

2021-07-25 15:20 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +        # self.log_object.write_log(
good spot  removed and replace with `raise` as suggested by @jamesnunnnhs

2021-07-25 15:20 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +                # self.log_object.write_log(
Removed commented out code

2021-07-25 15:21 UTC, aparimoo-nhs commented on terraform/stacks/mock-fhir-api/modules.tf
> +module "test_data" {
Refactored this whole , it is part of list-reconcillation stack  now.

2021-07-25 15:22 UTC, aparimoo-nhs commented on terraform/stacks/mock-fhir-api/modules.tf
> +module "s3" {
Refactored this whole module

2021-07-25 15:22 UTC, aparimoo-nhs commented on terraform/stacks/mock-fhir-api/terraform.tf
> +    key            = "list-reconciliation.tfstate"
Not required as it is a part of list-recon stack

2021-07-25 15:23 UTC, aparimoo-nhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +from utils.pds_api_service import FHIRAPIHelper
Done

2021-07-25 15:25 UTC, aparimoo-nhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +import boto3
Good spot , removed it now

2021-07-25 15:25 UTC, aparimoo-nhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> -
updated it as per style guide

2021-07-25 15:26 UTC, aparimoo-nhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +            pds_record = self.pds_api.get_pds_record(record.NhsNumber)
Yes, we have to refactor it  after we have all the credentials of FHIR API

2021-07-25 15:28 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +    def get_pds_record(self, nhs_id) -> dict:
Done updated to `nhs_number`

2021-07-25 15:28 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +            issue_code = self.parse_json_data("issue.[*].details.coding.[*].code")
No as per the API contract it is non 200 when there is an issue with response

2021-07-25 15:29 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +        :field is a jsonpath field
updated as google style

2021-07-25 15:29 UTC, aparimoo-nhs commented on requirements.txt
> +jsonpath-ng==1.5.3
Dont know how they got added, i have removed them

2021-07-25 15:30 UTC, aparimoo-nhs commented on terraform/modules/mock_fhir_api/api_gateway.tf
> +resource "aws_api_gateway_deployment" "mock_fhir_api_deployment" {
I have added the `aws_api_gateway_rest_api_policy` for access control that should it restrict to access publicly

2021-07-25 15:31 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +            return match_data[0]
updated  as per suggestion. classic copy paste example code :-).

2021-07-25 15:31 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +            print(str(e))
Done raise connection error

2021-07-25 15:32 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +class FHIRAPIHelper:
I have retained the `PDSAPIError` and got rid of s3 code of mock data

2021-07-26 12:03 UTC, aparimoo-nhs commented on Makefile
> +	docker run --rm -v $(PWD):/var/task -u $(shell id -u):$(shell id -g) -w="/var/task/" public.ecr.aws/sam/build-python3.8 /bin/python3 -m pip install -r requirements.txt -t ./api_lambda_layer/python/l
For deploying the mock api  for integration testing

2021-07-26 12:19 UTC, aparimoo-nhs commented on test/integrationtests/step_impl/data/A82023_GPR4LNA1.A1A
> +DOW~2~~EAST~~E1   1AA~~3~~
Good spot , wonder why my integration tests were failing. I was going through with Prem with test data fields. I accidentally may have deleted it

2021-07-26 12:27 UTC, aparimoo-nhs commented on test/unittests/conftest.py
> +    monkeypatch.setenv("PDS_API_URL", "http://mock_host_url:80000/patient")
Correct , it is not required. Removed it now.

2021-07-26 12:28 UTC, aparimoo-nhs commented on terraform/modules/lambda/LR-07/lambda.tf
> +
fixed

2021-07-26 12:34 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +    VERY_RESTRICTED = "V"
This is intentional as this service consumes API  whereas the other one is an API. If we import between these 2 then it will be tightly coupled. they need to be isolated

2021-07-26 12:37 UTC, aparimoo-nhs commented on lambdas/mock_fhir_api/app/main.py
> +    "U": filter_unrestricted_patients,
Yes , 
i suppose this looks much readable as oppose to the below as you suggested

```
    SensitiveMarkers.SENSITIVE.value: filter_restricted_patients,
    SensitiveMarkers.VERY_SENSITIVE.value: filter_very_restricted_patients,
    SensitiveMarkers.REDACTED.value: filter_redacted_patients,
    SensitiveMarkers.UNRESTRICTED.value: filter_unrestricted_patients
```

2021-07-26 12:42 UTC, aparimoo-nhs commented on packages/lambda_code/LR_12_pds_registration_status/lr_12_lambda_handler.py
> +                    if any(x in pds_record.get("sensitive") for x in ["R", "V", "REDACTED"]):
replaced it with ,  this is simplified now since we have use 2 loops so using generator makes it lean
 ```
any( marker.value in pds_record.get("sensitive") for marker in SensitiveMarkers )
```

2021-07-27 08:12 UTC, jamesnunnnhs commented on packages/lambda_code/LR_12_pds_registration_status/lr_12_lambda_handler.py
> +                    ):
Can you do this? `pds_record.get("sensitive") in SensitiveMarkers`

I'm struggling to see why you need this weird any/loop instead of a simple `pds_record.get("sensitive") in SensitiveMarkers` or `pds_record.get("sensitive") in list(SensitiveMarkers)`

If you must stick with this, there could be a bug related to substring searching `marker.value in pds_record.get("sensitive")`. Perhaps use `marker.value == pds_record.get("sensitive")`

2021-07-27 08:23 UTC, joeds13 requested changes

2021-07-27 08:23 UTC, joeds13 commented on terraform/modules/s3/LR-01.tf
>  resource "aws_s3_bucket_object" "inbound" {
Branch needs updating so we don't regress the fix on these objects

2021-07-27 09:16 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +            # Retrieve the issue code if the response is not 200
updated to check for status code

2021-07-27 09:28 UTC, aparimoo-nhs commented on packages/lambda_code/LR_12_pds_registration_status/lr_12_lambda_handler.py
> +                    ):
You cannot do `List(SensitiveMarkers)` , it is a class neither you can do `pds_record.get("sensitive") in SensitiveMarkers`  You still need to iterate  .  see below
```
class Test(Enum):
    R="Redacted"
    S="Restricted"

print(List(Test)) 
[<Test.R: 'Redacted'>, <Test.S: 'Restricted'>]
```


 I don't see it so complicated it is just one loop . however i think marker.value == pds_record.get("sensitive") is a good suggestion to avoid any substring
Let me know if it can be improved. open for suggestions

2021-07-27 09:45 UTC, jamesnunnnhs commented on packages/lambda_code/LR_12_pds_registration_status/lr_12_lambda_handler.py
> +                    ):
That's a shame Enum doesn't have `__iter__` just so you could loop through the values or convert to a list easily. Ok.

2021-07-27 09:48 UTC, aparimoo-nhs commented on requirements.txt
> +fastapi~=0.66.0
Good point , it is in separate file `mock_api_requirements.txt`

2021-07-27 09:56 UTC, aparimoo-nhs commented on terraform/modules/mock_fhir_api/iam.tf
> +      "arn:aws:lambda:*:*:function:${aws_lambda_function.mock_fhir_api_lambda.arn}"
Yes typo , corrected it now

2021-07-27 10:14 UTC, aparimoo-nhs commented on terraform/modules/mock_fhir_api/lambdas.tf
> +  output_path = "${path.module}/../../../api_lamdab_layer.zip"
done

2021-07-27 10:35 UTC, aparimoo-nhs commented on terraform/modules/s3/LR-01.tf
>  resource "aws_s3_bucket_object" "inbound" {
updated

2021-07-27 10:38 UTC, joeds13 commented on terraform/stacks/list-reconciliation/modules.tf
> +  role_arn         = local.terraform_deploy_role_arn["dev"]
This allows the role used by terraform to deploy to be able to call the mock_fhir_api, shouldn't this be the lambdas that actually need to make requests to this mock?

2021-07-27 10:42 UTC, joeds13 commented on terraform/modules/mock_fhir_api/iam.tf
> +  mock_fhir_api_bucket_arn = "arn:aws:s3:::${var.fhir_data_bucket}"
Pass ARN through, don't construct in string

2021-07-27 10:45 UTC, joeds13 requested changes

2021-07-27 10:45 UTC, joeds13 commented on terraform/stacks/mesh/locals.tf
> -  terraform_deploy_role_arn = {
Is this branch rebased from develop?

These should not be regressed

2021-07-27 11:34 UTC, aparimoo-nhs commented on terraform/stacks/mesh/locals.tf
> -  terraform_deploy_role_arn = {
Yes, i have rebased it with develop. Not sure whats happening. Will check again

2021-07-27 12:06 UTC, aparimoo-nhs commented on terraform/stacks/list-reconciliation/modules.tf
> +  role_arn         = local.terraform_deploy_role_arn["dev"]
This role arn string [ `"arn:aws:iam::{{AWSAccountID}}:role/{{AWSRoleName}}"`] is used for access control. Only resources with this role is allowed to access API  with api resource policy json.

2021-07-27 12:34 UTC, jamesnunnnhs approved these changes

2021-07-27 13:36 UTC, jamesnunnnhs approved these changes

2021-07-28 09:24 UTC, josh-scargill-nhsd commented on lambdas/mock_fhir_api/app/main.py
> +    "U": filter_unrestricted_patients,
I think it comes down to maintainability in this case. we don't want to manage these values in multiple places.

2021-07-28 09:34 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_12_pds_registration_status/lr_12_lambda_handler.py
> +                    # Deal with sensitive patients
Irrelevant comment, code is clear in what it does

2021-07-28 09:34 UTC, josh-scargill-nhsd commented on terraform/modules/mock_fhir_api/iam.tf
> +
🚌

2021-07-28 09:53 UTC, HarveyNHS reviewed
Please review

2021-07-28 09:53 UTC, HarveyNHS commented on pytest.ini
>      LR_10_STEP_FUNCTION_ARN=arn:aws:states:eu-west-2:123456789012:stateMachine:js_sf_test
Will this arn always be the same?

2021-07-28 09:53 UTC, HarveyNHS commented on test/unittests/lambdas/LR_07_pds_hydrate/test_LR_07_pds_hydrate.py
>          "PDS_Gender": "male",
Should this be capitalised aswell? male to Male?

2021-08-09 07:18 UTC, closed without merging