PCRM-3515-Test-Coverage
NHSDigital/list-reconciliation pull request #83
Opened 2021-07-29 10:00 UTC by premnhs

2021-07-29 10:40 UTC, HarveyNHS reviewed
Please review

2021-07-29 10:40 UTC, HarveyNHS commented on test/integrationtests/step_impl/data/LR_23/8000000008.json
> +{"system": {"name": "GP List Reconciliation", "source": "GP System", "patientId": "4e72d2e6-8ff0-433b-841b-6d15f10b07b1", "jobId": "17918df4-c811-46a1-a6e2-57979c825382"}, "patient": {"nhsNumber": "8
Will this always be the same? This won't dynamically change later on?

2021-07-29 10:40 UTC, HarveyNHS commented on test/integrationtests/step_impl/data/LR_23/9000000009.json
> +{"system": {"name": "GP List Reconciliation", "source": "GP System", "patientId": "604c4718-bebe-4ccc-9df3-736e49e5ca5e", "jobId": "17918df4-c811-46a1-a6e2-57979c825382"}, "patient": {"nhsNumber": "9
Same with this one

2021-07-29 10:40 UTC, HarveyNHS commented on test/integrationtests/step_impl/lr_02_lambda_val_parse.py
> +    use_waiters_check_object_exists(LR_01_BUCKET, expected_filename)
You need to wait for it twice?

2021-07-29 10:40 UTC, HarveyNHS commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
>      time.sleep(5)
Does this time.sleep allow the test to pass consistently?

2021-07-29 10:40 UTC, HarveyNHS commented on test/integrationtests/step_impl/lr_10_12_13_onlyon_pds.py
> +
Use Black to format the document

2021-07-29 10:40 UTC, HarveyNHS commented on test/integrationtests/step_impl/lr_15_lambda_cdd_file.py
> +@step("trigger lambda LR-15 and assert responsemetadata HTTPStatusCode response is <StatusCode>")
Have a space between 'responsemetadata'

2021-07-29 10:40 UTC, HarveyNHS commented on test/integrationtests/step_impl/lr_15_lambda_cdd_file.py
> +    time.sleep(10)
Same with this one - will this help to keep the pass rate consistent?

2021-07-29 11:01 UTC, premnhs commented on test/integrationtests/step_impl/data/LR_23/8000000008.json
> +{"system": {"name": "GP List Reconciliation", "source": "GP System", "patientId": "4e72d2e6-8ff0-433b-841b-6d15f10b07b1", "jobId": "17918df4-c811-46a1-a6e2-57979c825382"}, "patient": {"nhsNumber": "8
yes those two values will be updated on the code check this : `test/integrationtests/step_impl/lr_23_s3_patient_payload_json_file.py/update_exp_patient_record_lr23`

2021-07-29 11:08 UTC, premnhs commented on test/integrationtests/step_impl/lr_15_lambda_cdd_file.py
> +    time.sleep(10)
should do.. tried under different conditions

2021-07-29 11:09 UTC, premnhs commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
>      time.sleep(5)
yes should do

2021-07-30 08:23 UTC, joeds13 commented on test/integrationtests/step_impl/lr_02_lambda_val_parse.py
> +    time.sleep(10)
Can we poll here rather than sleep?

2021-07-30 08:25 UTC, HarveyNHS approved these changes
Approved

2021-07-30 08:26 UTC, joeds13 commented on test/integrationtests/step_impl/lr_02_lambda_val_parse.py
> +    time.sleep(10)
Can we poll here rather than sleep?

2021-07-30 08:26 UTC, joeds13 commented on test/integrationtests/specs/lr_10_12_13_lambda_onlyon_pds.spec
> +delete all s3 files in LR13
Shouldn't this have `*`?

2021-07-30 08:26 UTC, joeds13 commented on test/integrationtests/step_impl/lr_15_lambda_cdd_file.py
> +    time.sleep(10)
Can we use polling here rather than sleep?

2021-07-30 15:42 UTC, joeds13 commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
>      time.sleep(5)
Can we use polling here rather than sleep?

2021-08-03 14:55 UTC, josh-scargill-nhsd approved these changes

2021-08-04 09:44 UTC, joeds13 requested changes
Still several `time.sleep`s

2021-08-04 13:57 UTC, abbas-khan8 approved these changes

2021-08-05 10:04 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/lr_23_s3_patient_payload_json_file.py
> +        if patientid in filename.get("Key"):
Are you expecting the patientid to exist? If so then shouldn't you assert as such? If it doesn't exist there won't be anything to indicate that

2021-08-05 12:49 UTC, premnhs commented on test/integrationtests/step_impl/lr_23_s3_patient_payload_json_file.py
> +        if patientid in filename.get("Key"):
this is mainly to see if we are picking the correct patient record file to verify the details.

2021-08-09 07:32 UTC, joeds13 requested changes

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_02_lambda_val_parse.py
> +                    print(actual_key)
Remove print

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
> +    s3 = boto3.client("s3", REGION_NAME)
Redefinition of s3 client, duplicates line 17

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
> +            lambda: client.describe_execution(executionArn=executionarn)["status"] == "SUCCEEDED",
Should we not move the "SUCCEEDED" check into `check_success` of `polling.poll`?

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
> +        polling.poll(
Checking for files on S3 should be in a separate function and step, this function should complete successfully if the  Step Function status is "Succeeded" as described in the step definition

See https://github.com/NHSDigital/list-reconciliation/blob/develop/test/integrationtests/step_impl/lr_15_lambda_cdd_file.py#L76

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
> +        try:
Can we get the expected filenames, they should be in the output of the stepfunction? Then we can use the `boto` S3 `waiters` rather than this list polling

See https://github.com/NHSDigital/list-reconciliation/blob/develop/test/integrationtests/step_impl/lr_15_lambda_cdd_file.py#L103

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_02_lambda_val_parse.py
> +import time
Unused import?

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_10_12_13_onlyon_pds.py
> +            lambda: step_function_client.describe_execution(executionArn=execution_arn)["status"]
Should we not move the "SUCCEEDED" check into check_success of polling.poll?

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_10_12_13_onlyon_pds.py
> +        lr_13_response = polling.poll(
In replacing `use_waiters_check_object_exists` with this `list_objects_v2` polling, we no longer look for a specific file and we now will pass if any file appears in LR-13 during the test run. This is a regression and opens up a potential false positive passing case for the test.

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_15_lambda_cdd_file.py
> +import json
Duplicated import of line 1

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_23_s3_patient_payload_json_file.py
> +    try:
We are polling on `list_objects` again here, when it appears we have enough information, `patientid` etc, to be able to construct the expected filename and use an `s3` `waiter`

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +@step("setup step: connect to s3 buckets LR-20 and upload MESH data and check output in LR-22")
This step now does three separate actions, it should be broken into distinct steps/functions

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +        Messages.write_message("File upload for the respective GP Practice sucessfully")
As we are polling on `list_objects_v2` again, we don't know that the file arrived is for "`the respective GP Practice`" therefore this may lead to future issues when investigating this test as the file may not be the one we are expecting

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +    expected_string = obj.get("Key")
I think you want these four lines inside the loop starting line 51, with an assert guarding against falling through the loop

Ideally we could just replace all this looping with a waiter on the specific S3 file expected

2021-08-09 07:32 UTC, joeds13 commented on test/integrationtests/step_impl/lr_only_on_pds_steps.py
> +    file_count = lr_13_response["KeyCount"]
Can we do a `object_not_exists` waiter here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Waiter.ObjectNotExists
rather than trying to assert on the number of files?

2021-08-09 11:59 UTC, premnhs commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
> +            lambda: client.describe_execution(executionArn=executionarn)["status"] == "SUCCEEDED",
this is now replaced with the enhanced function on LR15

2021-08-09 11:59 UTC, premnhs commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
> +        polling.poll(
same here

2021-08-09 12:00 UTC, premnhs commented on test/integrationtests/step_impl/lr_10_11_13_onlyon_gppractice.py
> +        try:
this is now addressed by enhancing the lr15 : https://github.com/NHSDigital/list-reconciliation/blob/develop/test/integrationtests/step_impl/lr_15_lambda_cdd_file.py#L103

2021-08-10 09:17 UTC, premnhs commented on test/integrationtests/step_impl/lr_23_s3_patient_payload_json_file.py
> +    try:
Yeah ok updated it now and we already have polling and after that getting all the details required so was not using he s3 waiter. 
Btw..it was nhsno is on the filename and the `patientid` is within the file which later updates the expected content with the `patientid`

2021-08-10 12:30 UTC, joeds13 requested changes

2021-08-10 12:30 UTC, joeds13 commented on test/integrationtests/step_impl/lr_23_s3_patient_payload_json_file.py
> +    "connect to <lr_bucket> s3 bucket and ensure patient payload record file with nhsno <nhsno> is generated as expected <exp_datafile>"
`nhsno` is not an identifier we use elsewhere and may lead to confusion

`nhs_number` should be used as it's consistent with all the rest of the code

This should be updated in all references in this PR

2021-08-10 12:30 UTC, joeds13 commented on test/integrationtests/step_impl/lr_10_12_13_onlyon_pds.py
> +        lr_13_response = polling.poll(
This code is still doing a poll on the list objects

Is it not possible to know what file to expect and use a waiter?

2021-08-12 09:10 UTC, joeds13 approved these changes

2021-08-12 09:15 UTC, merged