PCRM-3525 - LR14 Send list rec results via MESH and email to PCSE
NHSDigital/list-reconciliation pull request #84
Opened 2021-07-29 14:39 UTC by jamesnunnnhs

2021-08-05 10:12 UTC, abbas-khan8 commented on packages/services/send_email_exchangelib.py
> +    log.info(f"Retrieved NHSMail credentials from AWS Secrets Manager for {username}")
Do we want this kind of logging to be included in the code base?

2021-08-05 10:57 UTC, jamesnunnnhs commented on packages/services/send_email_exchangelib.py
> +    log.info(f"Retrieved NHSMail credentials from AWS Secrets Manager for {username}")
I will actually use the log object from the lambda but LambdaApplication's logger handles logs from elsewhere - it should do, any other third party library might log or print and would need to be dealt with somehow.

2021-08-05 14:43 UTC, joeds13 requested changes
Adding some initial observations

There's also code in here that has been reviewed and changed under #99, are we going to get that merged first then rebase this, or do we want to pull in those changes here?

2021-08-05 14:43 UTC, joeds13 commented on pytest.ini
> +    LISTREC_EMAIL=pcrm.gplistreconciliation@nhs.net
We should use obviously test email addresses in test

2021-08-05 14:43 UTC, joeds13 commented on terraform/modules/lambda/LR-14/output.tf
> +output "region" {
Remove this output, it's not relevant

2021-08-05 14:43 UTC, joeds13 commented on terraform/modules/lambda/LR-14/output.tf
> +output "account_id" {
Remove this output, it's not relevant

2021-08-05 14:43 UTC, joeds13 commented on terraform/modules/ssm/email.tf
> +  value  = "password"
Should be `"To Replace"`as used in MESH and FHIR API params

2021-08-05 14:43 UTC, joeds13 commented on terraform/stacks/list-reconciliation/modules.tf
> +data "aws_kms_key" "mesh_kms" {
Move out of here to `data.tf`

2021-08-05 14:43 UTC, joeds13 commented on test_requirements.txt
> +mock==4.0.3
Has this been used?

2021-08-05 15:13 UTC, jamesnunnnhs commented
> Adding some initial observations
> 
> There's also code in here that has been reviewed and changed under #99, are we going to get that merged first then rebase this, or do we want to pull in those changes here?

I've just copied some code from there to here, so tbh the order doesn't matter, but I'm happy to say #99 first then this.

2021-08-06 13:45 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_14_send_list_rec_results/lr_14_lambda_handler.py
> +        timestamp = job.Timestamp.strftime("%H:%M:%S on %d-%m-%Y")
The date formatting in the spec is `DD/MM/YYYY` not `DD-MM-YYYY`.

2021-08-06 13:45 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_14_send_list_rec_results/lr_14_lambda_handler.py
> +    - {filelist}
Although this doesn't match the spec, can you clarify ben/Noor are happy with it? they might be and if so that's great :D

2021-08-06 13:45 UTC, josh-scargill-nhsd commented on packages/lambda_code/LR_15_process_demo_diffs/lr_15_lambda_handler.py
> +            key = f"{practice_code}-WIP-{job_id}-{patient_record.NhsNumber}-{now}.json"
WIP?

2021-08-06 13:45 UTC, josh-scargill-nhsd commented on packages/services/aws_mesh.py
> +# import logging
👀

2021-08-06 13:45 UTC, josh-scargill-nhsd commented on packages/services/aws_mesh.py
> +
🚌

2021-08-06 13:45 UTC, josh-scargill-nhsd commented on terraform/modules/ssm/outputs.tf
> +
🚌

2021-08-09 08:36 UTC, jamesnunnnhs commented on Makefile
> +	docker run --rm -v $(PWD):/var/task -u $(shell id -u):$(shell id -g) -w="/var/task/" public.ecr.aws/sam/build-python3.8 python -m pip install -r requirements.txt -t ./lambda_layer/python/lib/python3
This shouldn't matter because it's inside the container

2021-08-09 08:56 UTC, jamesnunnnhs commented on packages/lambda_code/LR_15_process_demo_diffs/lr_15_lambda_handler.py
> +            key = f"{practice_code}-WIP-{job_id}-{patient_record.NhsNumber}-{now}.json"
Yeah from the spec, although I can't find it now. Stands for Work Item Patient or something like that (I guess)

2021-08-09 12:04 UTC, aparimoo-nhs commented on requirements.txt
> +boto3==1.18.13
why lower version of boto?

2021-08-09 13:04 UTC, jamesnunnnhs commented on requirements.txt
> +boto3==1.18.13
dodgy merge, will fix

2021-08-09 13:05 UTC, jamesnunnnhs commented on packages/lambda_code/LR_14_send_list_rec_results/lr_14_lambda_handler.py
> +        unique_patients = {d.PatientId for d in diffs}
`{d.PatientId for d in diffs}` is a set comprehension, each item in a set is guaranteed to be unique - duplicates just overwrite existing.

2021-08-09 14:07 UTC, joeds13 approved these changes

2021-08-09 14:33 UTC, aparimoo-nhs approved these changes
just need to fix these test , all looks good to me

2021-08-09 15:17 UTC, josh-scargill-nhsd commented on test/unittests/lambdas/LR_14_send_list_rec_results/test_LR_14_send_list_rec_results.py
> +3 record/s being provided for the GP Practice to review and update.
I think it'd be good to have the test assert values other than 0, just to ensure it's returning a value correctly

2021-08-09 15:17 UTC, josh-scargill-nhsd commented on packages/services/send_email_exchangelib.py
> +from exchangelib import (
I could be blind but for this file, do we have unit tests?

2021-08-10 08:08 UTC, jamesnunnnhs commented on packages/services/send_email_exchangelib.py
> +from exchangelib import (
It's a third party lib, so I won't be testing it specifically. There's no point testing the email function anyway because I'd only have to mock it

2021-08-10 09:25 UTC, merged