PCRM-0000 Isolate LR-15 Test
NHSDigital/list-reconciliation pull request #97
Opened 2021-08-02 12:49 UTC by joeds13

2021-08-03 09:59 UTC, HarveyNHS requested changes

2021-08-03 10:04 UTC, joeds13 commented on test/integrationtests/step_impl/lr_15_lambda_cdd_file.py
> -access_key = os.getenv("AWS_PUBLIC_KEY")
I was basing it off the comment around this being used on Github and that `AWS_PUBLIC_KEY` and `AWS_PRIVATE_KEY` are non-standard Env variables for AWS `aws_access_key_id` and `aws_secret_access_key` respectively, so assumed it was all custom configuration in the previous Github builds

Are you able to checkout this PR locally and attempt running the tests on Windows please?

2021-08-04 13:58 UTC, HarveyNHS approved these changes
Approved

2021-08-05 09:38 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/lr_beforehooks.py
> +        while page["Count"] > 0:
This isn't explicitly decremented - is it updated when you call `page = table.scan(...`?

2021-08-05 09:49 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/test_helpers.py
> +        if key == "Items":
This will mask an implicit test (I presume) that `'Items'` must exist. Can you do this instead?

```job_items = [j for j in job_data['Items']]```

Doing that ^ will raise a `KeyError` if `'Items'` doesn't exist

2021-08-05 09:49 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/lr_beforehooks.py
> +        while page["Count"] > 0:
Looks like you  totally just stole that function from the top rated StackOverflow answer  so no prob, I trust them

2021-08-05 09:49 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/test_helpers.py
> +    )
Best use `datetime.strftime`. Also I think you missed hour

return `now.strftime('%Y%m%d%H%M%S%f')`

2021-08-05 09:49 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/test_helpers.py
> +            return describe_execution
Maybe raise an exception from this since it would be a fail for it not to succeed

2021-08-05 09:49 UTC, jamesnunnnhs commented on test/integrationtests/step_impl/test_helpers.py
> +        return False
Maybe raise an exception from this since it would be a fail for it not to succeed

2021-08-05 10:25 UTC, joeds13 commented on test/integrationtests/step_impl/test_helpers.py
> +            return describe_execution
Discussed with James to leave as is as it's consistent with the test code style

2021-08-05 10:25 UTC, joeds13 commented on test/integrationtests/step_impl/test_helpers.py
> +        return False
Discussed with James to leave as is as it's consistent with the test code style

2021-08-05 10:31 UTC, jamesnunnnhs approved these changes

2021-08-05 10:37 UTC, merged