PCRM-3724 Add FHIR Call
NHSDigital/list-reconciliation pull request #99
Opened 2021-08-02 15:38 UTC by aparimoo-nhs

Integration with FHIR API PDS call 
Added service for SSM Get and Put parameters
Updated unit tests

2021-08-03 09:46 UTC, joeds13 requested changes

2021-08-03 09:46 UTC, joeds13 commented on test/unittests/packages/utils/test_ssm.py
> +@pytest.mark.xfail
Does this test need fixing?

2021-08-03 09:46 UTC, joeds13 commented on test/unittests/packages/utils/test_ssm.py
> +        "pds_api_access_token": '{"access_token": "ZAbKUoARjkBAYFbfqdGdLtN9ucj6", "expires_in": "599", "token_type": "Bearer", "issued_at": "1627882540"}',
Can the `access_token` look more like a test string than a real string?

As in `'{"access_token": "this_is_a_test_token"}'`

2021-08-03 09:46 UTC, joeds13 commented on terraform/stacks/list-reconciliation/modules.tf
> +module "ssm_store" {
Prefer to keep the module name to be the same as the modules source directory name, so just `ssm`

2021-08-03 09:46 UTC, joeds13 commented on terraform/stacks/list-reconciliation/locals.tf
> +  pds_fhir_api_uri = {
These should be a single variable, for just the URL, as the paths won't change between environments spo can be stored as constants in Python

2021-08-03 09:46 UTC, joeds13 commented on terraform/stacks/list-reconciliation/locals.tf
> +    dev     = "https://ref.api.service.nhs.uk/personal-demographics/FHIR/R4"
We have no named environment `dev` so remove this

2021-08-03 09:46 UTC, joeds13 commented on terraform/stacks/list-reconciliation/locals.tf
> +    default = "https://ref.api.service.nhs.uk/personal-demographics/FHIR/R4",
Should default to the sandbox URL

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/ssm/pds_ssm.tf
> +resource "aws_ssm_parameter" "pds_fhir_api_private_key" {
File can be called `pds.tf` as we are in the `ssm` module so don't need the repetition

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/ssm/outputs.tf
> +output "pds_ssm" {
Should be more descriptive of the type, so something like `pds_ssm_parameters_path`

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/variables.tf
> +variable "pds_token_url" {
PLease include descriptions of these three variables

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/lambda.tf
> +  token_url                             = var.pds_token_url
Keep the variable name consistent: `pds_token_url = var.pds_token_url`

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/lambda.tf
> +  token_url                = var.pds_token_url
Keep the variable name consistent: pds_token_url = var.pds_token_url

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/lambda.tf
> +  pds_ssm                               = var.pds_ssm_prefix
Keep the variable name consistent: `pds_ssm_prefix = var.pds_ssm_prefix`

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/lambda.tf
> +  pds_ssm                  = var.pds_ssm_prefix
Keep the variable name consistent: `pds_ssm_prefix = var.pds_ssm_prefix`

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/LR-12/locals.tf
> +  param_name = "${var.lambda_name}-${var.suffix}"
Variable should be called `name`

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/LR-12/iam.tf
> +                  "arn:aws:ssm:eu-west-2:${data.aws_caller_identity.current.account_id}:parameter/${var.pds_ssm}/**"
As we have all three parameters created in terraform, we could have each named rather than using a wildcard

Then we could have separate statements, controlling fine grained controls on each of them, for example only allowing the put on the token variable

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/LR-07/locals.tf
> +  ssm_name = "${var.lambda_name}-${var.suffix}"
Just be `name`

2021-08-03 09:46 UTC, joeds13 commented on terraform/modules/lambda/LR-07/iam.tf
> +                  "arn:aws:ssm:eu-west-2:${data.aws_caller_identity.current.account_id}:parameter/${var.pds_ssm}/*"
As we have all three parameters created in terraform, we could have each named rather than using a wildcard

Then we could have separate statements, controlling fine grained controls on each of them, for example only allowing the put on the token variable

2021-08-03 09:46 UTC, joeds13 commented on pytest.ini
> +    SSM_STORE_PREFIX=/ash-dev/pds/
Generic name not `ash-dev`

2021-08-03 09:46 UTC, joeds13 commented on packages/utils/ssm.py
> +    ssm_client = boto3.client("ssm", region_name=region)
Initialise the ssm client in the top level scope and then use it in the two functions

Means boto3 is initialised at application startup rather than every function call

2021-08-03 09:46 UTC, joeds13 commented on packages/utils/pds_api_service.py
> +            # TODO Change to prod before merge
Do this TODO?

2021-08-03 09:46 UTC, joeds13 commented on packages/utils/pds_api_service.py
> +    def __init__(self, system_config, logger):
Passing in the LambdaApplication system_config and logger tightly couples this code to the spine-aws-common implementation

It's a significant change but it we be better to only pass in the configuration specific to the FHIR API

Also it's debatable if there should be any logging in this class, as it's not a "business logic" piece of code and should just be passing errors back up to the caller

2021-08-03 09:46 UTC, joeds13 commented on packages/utils/pds_api_service.py
> +            raise PDSAPIError("System config not available, exiting")
There's some naming inconsistency that may confuse users inexperienced with this area with having both `PDSAPI` and `FHIRAPI` used interchangeably

2021-08-03 12:41 UTC, joeds13 commented on packages/utils/pds_api_service.py
> +                put_ssm_params(
Are we worried about any race conditions here, if this called in two Lambdas, will they fight? Would a collision even cause an issue?

2021-08-03 16:48 UTC, abbas-khan8 commented on terraform/modules/lambda/variables.tf
> +
Unnecessary extra line here?

2021-08-04 14:04 UTC, HarveyNHS approved these changes
Approved

2021-08-04 14:18 UTC, aparimoo-nhs commented on packages/utils/pds_api_service.py
> +                put_ssm_params(
I didn't see any issue so far , looking at forum some have noticed exception 'TooManyUpdate'. i have handled that in code to retry if '`TooManyUpdate`' exception is raised

2021-08-04 14:23 UTC, aparimoo-nhs commented on terraform/stacks/list-reconciliation/locals.tf
> +  pds_fhir_api_uri = {
that would tie code with url if the version changes , the way it looks that version no is appended to the path. if version changes code needs changing

2021-08-04 14:32 UTC, joeds13 commented on terraform/stacks/list-reconciliation/locals.tf
> +  pds_fhir_api_uri = {
If the version in the API URI changes, then that will be a breaking contract change which would result in the code needing to change? 
Therefore it makes sense that the code owns what version(s) it supports rather than it just being passed along in the URL as part of the configuration

2021-08-04 14:34 UTC, joeds13 commented on terraform/modules/ssm/pds.tf
> +  value     = "test"
`value     = "To Replace"`

Matches MESH Module: https://github.com/NHSDigital/spine-core-aws-common/blob/develop/terraform/mesh_aws/ssm_config.tf

2021-08-04 14:34 UTC, joeds13 commented on terraform/modules/ssm/pds.tf
> +  value     = "test"
`value     = "To Replace"`

Matches MESH Module: https://github.com/NHSDigital/spine-core-aws-common/blob/develop/terraform/mesh_aws/ssm_config.tf

2021-08-04 18:00 UTC, abbas-khan8 approved these changes

2021-08-05 09:48 UTC, joeds13 requested changes

2021-08-05 09:48 UTC, joeds13 commented on terraform/stacks/list-reconciliation/locals.tf
> +    preprod = ""
If this is empty, Integration Tests in PreProd will fail, should it be sandbox or ref?

If it's ref we'll need to get the creds setup after merge

As you're editing it, I'd call this variable `pds_fhir_api_url` not `uri` to be more accurate

2021-08-05 10:50 UTC, jamesnunnnhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +            error_response = log_dynamodb_error(self.log_object, job_id, str(err), msg)
Are we still supposed to be logging errors to dynamo? I thought we were dropping that

2021-08-05 10:50 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +        if not isinstance(system_config, dict):
How about adding a typehint for system_config and a bit of documentation about how it's used or behaves.

2021-08-05 10:50 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +                    )
Isn't it possible for this to enter a non-exiting loop until the lambda times out? Maybe put a retry on this? 

See `utils.retry_func` for a retryer

2021-08-05 10:50 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +    def get_pds_record(self, nhs_number, job_id) -> dict:
Can you add some typehints for this and if it's possible, a return type as expected like `Dict[str, str]` or even define a type and return that?

2021-08-05 10:50 UTC, jamesnunnnhs commented on packages/utils/pds_api_service.py
> +            return {}
I would tend to return `None` rather than an empty object unless you'd expect to be able to process the empty object later in the caller

2021-08-05 10:50 UTC, jamesnunnnhs commented on pytest.ini
> +    SSM_STORE_PREFIX=/dev/pds/
should the prefix include the trailing `/`? I think so because it looks like in the iam definition you add it explicitly

2021-08-05 10:50 UTC, jamesnunnnhs commented on terraform/modules/lambda/LR-12/iam.tf
> +                  "arn:aws:ssm:eu-west-2:${data.aws_caller_identity.current.account_id}:parameter/${var.pds_ssm_prefix}/**"
Two `*`s? Does it handle that or is it an error?

2021-08-05 10:50 UTC, jamesnunnnhs commented on terraform/modules/lambda/LR-12/lambda.tf
> +      SSM_STORE_PREFIX                        = "/${var.pds_ssm_prefix}/"
Just check the prefix trailing `/` per my other comments

2021-08-05 10:50 UTC, jamesnunnnhs commented on terraform/modules/lambda/lambda.tf
> +
I think the terraform gods won't like this newline

2021-08-05 10:50 UTC, jamesnunnnhs commented on terraform/modules/ssm/outputs.tf
> +  value = "${var.prefix}/pds"
Check how this plays with the prefix having included the trailing `/`

2021-08-05 10:53 UTC, aparimoo-nhs commented on packages/lambda_code/LR_07_pds_hydrate/lr_07_lambda_handler.py
> +            error_response = log_dynamodb_error(self.log_object, job_id, str(err), msg)
not in this story

2021-08-05 12:11 UTC, aparimoo-nhs commented on pytest.ini
> +    SSM_STORE_PREFIX=/dev/pds/
This is for test so i am passing the prefix

2021-08-06 06:51 UTC, joeds13 approved these changes

2021-08-06 10:37 UTC, merged